#
#   Create .dsb directory
#

dsblib_which  md5sum
dsblib_check_compose_version

declare -r MYVERSION="${1:-3.3}"
declare -r MYBOX="$DSB_WORKDIR/.dsb"
declare -r MYGLOBALS="globals.yaml"


declare    MYPROJECTID="${RANDOM}|$( cd -- "$DSB_WORKDIR"; pwd -P )"
if hash date ; then
    MYPROJECTID="$(  date +%s 2>/dev/null )|${MYPROJECTID}"
fi
MYPROJECTID="$( echo "${MYPROJECTID}" | md5sum - )"
MYPROJECTID="${MYPROJECTID:0:32}"


declare MYHOMEVOLS="# "
if [ "$DSBLIB_OSTYPE" != LINUX ]; then
    MYHOMEVOLS=
fi


if [ -d "$MYBOX" ]; then
    dsblib_error_exit "Directory '$MYBOX' already exists" 
fi

if dsb_set_box --check ; then
    dsblib_error_exit "The current directory is located in the context of the '$DSB_BOX'\n"
fi

dsblib_exec mkdir "$MYBOX"
dsblib_exec cp -pPR "$DSBLIB_LIB"/init/. "$MYBOX"  # POSIX

declare MYMTU=$( docker network inspect bridge --format '{{index .Options "com.docker.network.driver.mtu"}}' )
MYMTU="${MYMTU:-1450}"


echo "version: '${MYVERSION}'

networks:
  dsbnet:
    driver: bridge
    #
    # This is a workaround for the problem "containers in docker does not get same MTU as host"
    # see: https://github.com/moby/moby/issues/22297
    #
    # You must also set appropriate MTU in the file /etc/docker/daemon.json:
    #
    # {
    #   \"mtu\": ${MYMTU}
    # }
    #
    driver_opts:
      com.docker.network.driver.mtu: ${MYMTU}
" > "$MYBOX/compose/$MYGLOBALS"


echo "#
#   Compose & Dsb variables
#
#   This file is a Bash source file.
#   The variables set in this file override the variables in the .env file,
#   if the latter is used in the configuration.
#   
#   See also: 
#   https://docs.docker.com/compose/environment-variables/
#   https://docs.docker.com/compose/reference/envvars/
#
#   Advanced Bash-Scripting Guide: https://tldp.org/LDP/abs/html/variables.html
#
##################


#
#   Сustomize your project by defining additional Сompose .yaml files separated by ':'.
#   Example:
#
#       COMPOSE_FILE=\"${MYGLOBALS}:php.yaml:nginx.yaml\"
#
#   File '${MYGLOBALS}' is a must.
#
COMPOSE_FILE=\"${MYGLOBALS}\"


#   All Dsb projects in the host system must have different DSB_PROJECT_IDs.
#   Before changing the value of the DSB_PROJECT_ID variable,
#   run 'dsb down' and remove all named volumes in the project.
#
DSB_PROJECT_ID=\"${MYPROJECTID}\"


#   The variable is used as a mounted directory
#   in the yaml files generated by the 'dsb yaml' subcommand:
#
#    volumes:
#      - \$DSB_SPACE:/dsbspace
#
#   Default variable value: full path of the Dsb project root directory
#
DSB_SPACE=\"\$DSB_ROOT\"


# NOTE: All yaml-files must have the same version 
#
DSB_COMPOSE_FILE_VERSION=\"${MYVERSION}\"


#   Uncomment this variable to enable Production Mode,
#
# DSB_PROD_MODE=true


#   Store dsbuser home directories on named volumes
#
${MYHOMEVOLS}DSB_HOME_VOLUMES=true


#   Container shutdown timeout in seconds
#
DSB_SHUTDOWN_TIMEOUT=10


#   File mode creation mask for 'dsb...' commands and 'dsb sh', 'dsb root' sessions/commands.
#   By default, the current umask value of the host command line is used.
#
# DSB_UMASK_SH=002
# DSB_UMASK_ROOT=022


#   Service names for dsb... commands
#   (from .yaml files)
#
# DSB_SERVICE_MONGO=mongo
# DSB_SERVICE_MYSQL=mysql
# DSB_SERVICE_NODE=node
# DSB_SERVICE_PHP=php
# DSB_SERVICE_POSTGRES=postgres
# DSB_SERVICE_REDIS=redis
# DSB_SERVICE_RUBY=ruby
# DSB_SERVICE_PYTHON=python
# DSB_SERVICE_PYTHON2=python2
# DSB_SERVICE_PYTHON3=python3
" > "$MYBOX/compose/$DSBLIB_DSBENV"

dsblib_exec rm -f "$MYBOX/compose/.gitkeep"
dsblib_exec chmod -R u+rX   "$MYBOX"
dsblib_exec chmod -R go-rwx "$MYBOX"

dsblib_green_message "Directory '$MYBOX' is initialized"
dsblib_exit